#!/usr/bin/env bash
# forgeplan — lib/git-ops.sh
# Branch, commit, push, interactive review.

# Globals set by this module:
#   GIT_BRANCH_NAME — name of the created/checked-out branch
#   GIT_COMMIT_SHA  — full commit SHA after commit

GIT_BRANCH_NAME=""
GIT_COMMIT_SHA=""

# ==========================================================================
# Slug generator
# ==========================================================================

# ---------------------------------------------------------------------------
# _git_slugify <text>
# Convert text to a branch-safe slug: lowercase, hyphens, max 50 chars.
# ---------------------------------------------------------------------------
_git_slugify() {
  local text="$1"
  printf '%s' "$text" \
    | tr '[:upper:]' '[:lower:]' \
    | tr ' _' '--' \
    | sed 's/[^a-z0-9-]//g' \
    | sed 's/--*/-/g' \
    | sed 's/^-//;s/-$//' \
    | cut -c1-50
}

# ==========================================================================
# Preflight
# ==========================================================================

# ---------------------------------------------------------------------------
# git_preflight <repo_root>
# Validate git repo, clean working tree, remote exists.
# ---------------------------------------------------------------------------
git_preflight() {
  local repo_root="$1"

  # Check is git repo
  if ! git -C "$repo_root" rev-parse --git-dir > /dev/null 2>&1; then
    log_error "${repo_root} is not a Git repository."
    exit 4
  fi

  # Check working tree is clean
  if [[ -n "$(git -C "$repo_root" status --porcelain 2>/dev/null)" ]]; then
    log_error "Working tree has uncommitted changes. Commit or stash them first."
    exit 4
  fi

  # Check remote exists
  if ! git -C "$repo_root" remote get-url "${GIT_REMOTE}" > /dev/null 2>&1; then
    log_error "Git remote '${GIT_REMOTE}' not found."
    exit 4
  fi

  log_info "Git preflight passed: clean working tree, remote '${GIT_REMOTE}' accessible."
}

# ==========================================================================
# Branch creation
# ==========================================================================

# ---------------------------------------------------------------------------
# git_create_branch <wp_id> <wp_subject>
# Create or checkout branch: feature/WP-<id>-<slug>
# ---------------------------------------------------------------------------
git_create_branch() {
  local wp_id="$1"
  local wp_subject="$2"

  local slug
  slug=$(_git_slugify "$wp_subject")
  GIT_BRANCH_NAME="feature/WP-${wp_id}-${slug}"

  # Fetch latest
  git -C "$REPO_ROOT" fetch "${GIT_REMOTE}" "${GIT_BASE_BRANCH}" --quiet 2>/dev/null || true

  # Check if branch exists locally
  if git -C "$REPO_ROOT" show-ref --verify --quiet "refs/heads/${GIT_BRANCH_NAME}" 2>/dev/null; then
    log_warn "Branch already exists locally. Checking out existing branch."
    git -C "$REPO_ROOT" checkout "${GIT_BRANCH_NAME}" --quiet
    return 0
  fi

  # Check if branch exists on remote
  if git -C "$REPO_ROOT" show-ref --verify --quiet "refs/remotes/${GIT_REMOTE}/${GIT_BRANCH_NAME}" 2>/dev/null; then
    log_warn "Branch already exists on remote. Checking out existing branch."
    git -C "$REPO_ROOT" checkout -b "${GIT_BRANCH_NAME}" "${GIT_REMOTE}/${GIT_BRANCH_NAME}" --quiet
    return 0
  fi

  # Create new branch from base
  git -C "$REPO_ROOT" checkout -b "${GIT_BRANCH_NAME}" "${GIT_REMOTE}/${GIT_BASE_BRANCH}" --quiet
  log_info "Created branch: ${GIT_BRANCH_NAME}"
}

# ==========================================================================
# Commit
# ==========================================================================

# ---------------------------------------------------------------------------
# git_stage_and_commit <wp_id> <wp_subject> <result> <validation_output>
# Stage all changes and commit with structured message.
# ---------------------------------------------------------------------------
git_stage_and_commit() {
  local wp_id="$1"
  local wp_subject="$2"
  local result="$3"
  local validation_output="${4:-}"

  # Stage all changes
  git -C "$REPO_ROOT" add -A

  # Build commit message
  local prefix subject_line body

  case "$result" in
    SUCCESS)
      prefix=""
      subject_line="feat(WP-${wp_id}): ${wp_subject}"
      body="Auto-generated by forgeplan from OpenProject WP #${wp_id}
Result: SUCCESS
Cost: \$${CLAUDE_COST_USD:-unknown} | Turns: ${CLAUDE_NUM_TURNS:-unknown}"
      ;;
    PARTIAL)
      prefix="[WIP] "
      subject_line="${prefix}feat(WP-${wp_id}): ${wp_subject}"
      local val_truncated="${validation_output}"
      if [[ ${#val_truncated} -gt 500 ]]; then
        val_truncated="${val_truncated:0:500}..."
      fi
      body="Auto-generated by forgeplan from OpenProject WP #${wp_id}
Result: PARTIAL - validation failed

Validation output:
${val_truncated}"
      ;;
    FAILURE)
      if [[ "${CLAUDE_FAILURE_REASON:-}" == "timeout" ]]; then
        prefix="[TIMEOUT] "
      else
        prefix="[FAILED] "
      fi
      subject_line="${prefix}feat(WP-${wp_id}): ${wp_subject}"
      body="Auto-generated by forgeplan from OpenProject WP #${wp_id}
Generation timed out after ${GENERATION_TIMEOUT:-600}s. Files may be incomplete."
      ;;
  esac

  local commit_msg="${subject_line}

${body}"

  git -C "$REPO_ROOT" commit -m "$commit_msg" --quiet
  GIT_COMMIT_SHA=$(git -C "$REPO_ROOT" rev-parse HEAD)

  log_info "Committed: $(echo "$GIT_COMMIT_SHA" | cut -c1-8) ${subject_line}"
}

# ==========================================================================
# Push
# ==========================================================================

# ---------------------------------------------------------------------------
# git_push
# Push current branch to remote. Returns 4 on failure.
# ---------------------------------------------------------------------------
git_push() {
  local push_output
  push_output=$(git -C "$REPO_ROOT" push "${GIT_REMOTE}" "${GIT_BRANCH_NAME}" 2>&1) || {
    local rc=$?
    if echo "$push_output" | grep -qi "rejected"; then
      log_error "Push rejected. Branch may have diverged."
    elif echo "$push_output" | grep -qi "permission denied\|403\|authentication"; then
      log_error "Push permission denied. Check GIT_HOST_TOKEN."
    else
      log_error "Push failed: ${push_output}"
    fi
    return 4
  }

  log_info "Pushed branch ${GIT_BRANCH_NAME} to ${GIT_REMOTE}"
  return 0
}

# ==========================================================================
# Interactive review (I-7)
# ==========================================================================

# ---------------------------------------------------------------------------
# git_interactive_review <repo_root>
# Show diff, prompt for action. Returns 0=accept, 1=reject.
# ---------------------------------------------------------------------------
git_interactive_review() {
  local repo_root="$1"

  while true; do
    echo ""
    echo "=== Generated Changes ==="
    git -C "$repo_root" diff --stat
    git -C "$repo_root" ls-files --others --exclude-standard | sed 's/^/  new file: /'
    echo ""

    # Show full diff in pager
    git -C "$repo_root" diff --color | "${PAGER:-less -R}" 2>/dev/null || git -C "$repo_root" diff

    echo ""
    echo "Review complete. Choose an action:"
    echo "  [a] Accept — commit and continue pipeline"
    echo "  [e] Edit   — open \$EDITOR to make changes, then re-review"
    echo "  [r] Reject — discard all changes, skip this WP"
    echo "  [s] Shell  — drop to a shell, return to this prompt when done"
    printf "Choice [a/e/r/s]: "

    local choice
    read -r choice

    case "$choice" in
      a|A)
        log_info "Changes accepted by reviewer"
        return 0
        ;;
      e|E)
        local editor="${EDITOR:-vi}"
        log_info "Opening ${editor} for manual edits..."
        (cd "$repo_root" && "$editor" .)
        echo "Editor closed. Re-reviewing..."
        ;;
      r|R)
        log_warn "Changes rejected by reviewer. Discarding."
        git -C "$repo_root" checkout -- . 2>/dev/null || true
        git -C "$repo_root" clean -fd 2>/dev/null || true
        return 1
        ;;
      s|S)
        log_info "Dropping to shell. Type 'exit' to return to review."
        (cd "$repo_root" && "${SHELL:-bash}")
        echo "Shell exited. Re-reviewing..."
        ;;
      *)
        echo "Invalid choice. Enter a, e, r, or s."
        ;;
    esac
  done
}
