#!/usr/bin/env bash
# forgeplan — lib/pr-creator.sh
# PR creation: GitHub, GitLab, Bitbucket. Rollback support.

# Globals set by this module:
#   PR_URL — web URL of the created (or existing) PR

PR_URL=""

# ==========================================================================
# Token resolution — use CLI auth (gh, glab) or fallback to env
# ==========================================================================

# ---------------------------------------------------------------------------
# _resolve_git_token <host_type>
# Resolve auth token from CLI tools, falling back to GIT_HOST_TOKEN env var.
# ---------------------------------------------------------------------------
_resolve_git_token() {
  local host_type="$1"

  case "$host_type" in
    github)
      # gh auth token (GitHub CLI)
      if command -v gh > /dev/null 2>&1; then
        local token
        token=$(gh auth token 2>/dev/null || echo "")
        if [[ -n "$token" ]]; then
          echo "$token"
          return 0
        fi
      fi
      ;;
    gitlab)
      # glab auth (GitLab CLI)
      if command -v glab > /dev/null 2>&1; then
        local token
        token=$(glab auth status -t 2>&1 | grep -oP 'Token: \K\S+' || echo "")
        if [[ -n "$token" ]]; then
          echo "$token"
          return 0
        fi
      fi
      ;;
  esac

  # Fallback to env var
  echo "${GIT_HOST_TOKEN:-}"
}

# ==========================================================================
# PR body builder
# ==========================================================================

# ---------------------------------------------------------------------------
# pr_build_body <wp_id> <result> <changed_files>
# Construct PR body markdown.
# ---------------------------------------------------------------------------
pr_build_body() {
  local wp_id="$1"
  local result="$2"
  local changed_files="$3"

  local files_list=""
  if [[ -n "$changed_files" ]]; then
    files_list=$(echo "$changed_files" | sed 's/^/- `/' | sed 's/$/`/')
  fi

  local notes="- This PR was auto-generated from OpenProject work package #${wp_id}.
- Review carefully before merging."

  if [[ "$result" == "PARTIAL" ]]; then
    notes+=$'\n'"- ⚠️ Validation failed. See commit message for details."
  fi

  cat <<EOF
## Auto-generated by forgeplan

**OpenProject WP:** #${wp_id} — [View in OpenProject](${OP_BASE_URL}/work_packages/${wp_id})
**Result:** ${result}
**Generated by:** ${CLAUDE_MODEL:-unknown}

### Files Changed
${files_list:-No files listed.}

### Notes
${notes}
EOF
}

# ==========================================================================
# Platform dispatchers
# ==========================================================================

# ---------------------------------------------------------------------------
# pr_create <wp_id> <wp_subject> <result> <branch_name> <changed_files> <repo_slug> <host_type> <base_branch>
# Dispatch to platform-specific PR creation.
# ---------------------------------------------------------------------------
pr_create() {
  local wp_id="$1"
  local wp_subject="$2"
  local result="$3"
  local branch_name="$4"
  local changed_files="$5"
  local repo_slug="${6:-}"
  local host_type="${7:-}"
  local base="${8:-main}"

  if [[ -z "$repo_slug" ]]; then
    log_error "Cannot determine repo slug from git remote. Check your layer's path."
    return 1
  fi

  if [[ -z "$host_type" ]]; then
    log_error "Cannot determine git host type from remote URL."
    return 1
  fi

  # Resolve auth token from CLI tools or env
  GIT_HOST_TOKEN="$(_resolve_git_token "$host_type")"
  if [[ -z "$GIT_HOST_TOKEN" ]]; then
    log_info "Skipping PR creation (no auth token — run 'gh auth login' or 'glab auth login')"
    return 0
  fi

  # Set for platform-specific functions
  GIT_HOST_REPO="$repo_slug"

  # Resolve reviewers from config
  if [[ -n "${FP_LAYERS_JSON:-}" ]]; then
    REVIEWERS=$(echo "$FP_LAYERS_JSON" | jq -r '.reviewers // [] | join(",")' 2>/dev/null || echo "")
  fi

  local title
  case "$result" in
    PARTIAL) title="[WIP] feat(WP-${wp_id}): ${wp_subject}" ;;
    *)       title="feat(WP-${wp_id}): ${wp_subject}" ;;
  esac

  local body
  body=$(pr_build_body "$wp_id" "$result" "$changed_files")

  case "${host_type}" in
    github)   pr_create_github "$title" "$body" "$branch_name" "$base" "$wp_id" ;;
    gitlab)   pr_create_gitlab "$title" "$body" "$branch_name" "$base" "$wp_id" ;;
    bitbucket) pr_create_bitbucket "$title" "$body" "$branch_name" "$base" "$wp_id" ;;
    *)
      log_error "Unknown git host type: ${host_type}. Supported: github, gitlab, bitbucket"
      return 1
      ;;
  esac
}

# ==========================================================================
# GitHub
# ==========================================================================

# ---------------------------------------------------------------------------
# pr_create_github <title> <body> <branch> <base> <wp_id>
# ---------------------------------------------------------------------------
pr_create_github() {
  local title="$1"
  local body="$2"
  local branch="$3"
  local base="$4"
  local wp_id="$5"

  local api_url="https://api.github.com/repos/${GIT_HOST_REPO}"

  # Create PR
  local pr_body
  pr_body=$(jq -n -c \
    --arg title "$title" \
    --arg body "$body" \
    --arg head "$branch" \
    --arg base "$base" \
    '{title: $title, body: $body, head: $head, base: $base}')

  local response http_code
  local tmp_body
  tmp_body=$(mktemp)
  http_code=$(curl --silent --show-error --max-time 30 \
    -w '%{http_code}' \
    -o "$tmp_body" \
    -H "Authorization: Bearer ${GIT_HOST_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -X POST \
    --data "$pr_body" \
    "${api_url}/pulls" 2>/dev/null) || true
  response=$(cat "$tmp_body")
  rm -f "$tmp_body"

  if [[ "$http_code" == "201" ]]; then
    PR_URL=$(echo "$response" | jq -r '.html_url')
    local pr_number
    pr_number=$(echo "$response" | jq -r '.number')
    log_info "PR created: ${PR_URL}"

    # Add reviewers
    _github_add_reviewers "$api_url" "$pr_number"
    # Add labels
    _github_add_labels "$api_url" "$pr_number" "$wp_id"
    return 0
  fi

  # Handle 422 — PR already exists
  if [[ "$http_code" == "422" ]]; then
    log_warn "PR may already exist. Searching..."
    _github_find_existing_pr "$api_url" "$branch"
    return 0
  fi

  log_error "GitHub PR creation failed (HTTP ${http_code}): $(echo "$response" | jq -r '.message // empty')"
  return 1
}

_github_add_reviewers() {
  local api_url="$1"
  local pr_number="$2"

  if [[ -z "${REVIEWERS:-}" ]]; then
    return 0
  fi

  local reviewers_json
  reviewers_json=$(echo "$REVIEWERS" | tr ',' '\n' | jq -R . | jq -sc '{reviewers: .}')

  curl --silent --max-time 15 \
    -H "Authorization: Bearer ${GIT_HOST_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -X POST \
    --data "$reviewers_json" \
    "${api_url}/pulls/${pr_number}/requested_reviewers" > /dev/null 2>&1 || true

  log_debug "Reviewers requested: ${REVIEWERS}"
}

_github_add_labels() {
  local api_url="$1"
  local pr_number="$2"
  local wp_id="$3"

  local labels_json
  labels_json=$(jq -n -c --arg wp "wp-${wp_id}" '{"labels": ["auto-generated", $wp]}')

  curl --silent --max-time 15 \
    -H "Authorization: Bearer ${GIT_HOST_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -X POST \
    --data "$labels_json" \
    "${api_url}/issues/${pr_number}/labels" > /dev/null 2>&1 || true

  log_debug "Labels added: auto-generated, wp-${wp_id}"
}

_github_find_existing_pr() {
  local api_url="$1"
  local branch="$2"

  local response
  response=$(curl --silent --max-time 15 \
    -H "Authorization: Bearer ${GIT_HOST_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    "${api_url}/pulls?head=${GIT_HOST_REPO%%/*}:${branch}&state=open" 2>/dev/null) || true

  local existing_url
  existing_url=$(echo "$response" | jq -r '.[0].html_url // empty')

  if [[ -n "$existing_url" ]]; then
    PR_URL="$existing_url"
    log_warn "PR already exists: ${PR_URL}. New commit pushed to existing PR."
  else
    log_warn "Could not find existing PR for branch ${branch}"
  fi
}

# ==========================================================================
# GitLab
# ==========================================================================

# ---------------------------------------------------------------------------
# pr_create_gitlab <title> <body> <branch> <base> <wp_id>
# ---------------------------------------------------------------------------
pr_create_gitlab() {
  local title="$1"
  local body="$2"
  local branch="$3"
  local base="$4"
  local wp_id="$5"

  # URL-encode project path
  local encoded_repo
  encoded_repo=$(printf '%s' "$GIT_HOST_REPO" | jq -sRr @uri)

  local api_url="https://gitlab.com/api/v4/projects/${encoded_repo}"

  local mr_body
  mr_body=$(jq -n -c \
    --arg title "$title" \
    --arg desc "$body" \
    --arg source "$branch" \
    --arg target "$base" \
    --arg labels "auto-generated,wp-${wp_id}" \
    '{title: $title, description: $desc, source_branch: $source, target_branch: $target, labels: $labels}')

  local response http_code
  local tmp_body
  tmp_body=$(mktemp)
  http_code=$(curl --silent --show-error --max-time 30 \
    -w '%{http_code}' \
    -o "$tmp_body" \
    -H "PRIVATE-TOKEN: ${GIT_HOST_TOKEN}" \
    -H "Content-Type: application/json" \
    -X POST \
    --data "$mr_body" \
    "${api_url}/merge_requests" 2>/dev/null) || true
  response=$(cat "$tmp_body")
  rm -f "$tmp_body"

  if [[ "$http_code" == "201" ]]; then
    PR_URL=$(echo "$response" | jq -r '.web_url')
    log_info "MR created: ${PR_URL}"

    if [[ -n "${REVIEWERS:-}" ]]; then
      log_warn "GitLab reviewers require numeric user IDs. Username-based assignment not supported."
    fi
    return 0
  fi

  log_error "GitLab MR creation failed (HTTP ${http_code}): $(echo "$response" | jq -r '.message // empty')"
  return 1
}

# ==========================================================================
# Bitbucket
# ==========================================================================

# ---------------------------------------------------------------------------
# pr_create_bitbucket <title> <body> <branch> <base> <wp_id>
# ---------------------------------------------------------------------------
pr_create_bitbucket() {
  local title="$1"
  local body="$2"
  local branch="$3"
  local base="$4"
  local wp_id="$5"

  local api_url="https://api.bitbucket.org/2.0/repositories/${GIT_HOST_REPO}"

  # Build reviewers array
  local reviewers_json="[]"
  if [[ -n "${REVIEWERS:-}" ]]; then
    reviewers_json=$(echo "$REVIEWERS" | tr ',' '\n' | jq -R '{username: .}' | jq -sc '.')
  fi

  local pr_body
  pr_body=$(jq -n -c \
    --arg title "$title" \
    --arg desc "$body" \
    --arg source "$branch" \
    --arg dest "$base" \
    --argjson reviewers "$reviewers_json" \
    '{
      title: $title,
      description: $desc,
      source: {branch: {name: $source}},
      destination: {branch: {name: $dest}},
      reviewers: $reviewers
    }')

  local response http_code
  local tmp_body
  tmp_body=$(mktemp)
  http_code=$(curl --silent --show-error --max-time 30 \
    -w '%{http_code}' \
    -o "$tmp_body" \
    -H "Authorization: Bearer ${GIT_HOST_TOKEN}" \
    -H "Content-Type: application/json" \
    -X POST \
    --data "$pr_body" \
    "${api_url}/pullrequests" 2>/dev/null) || true
  response=$(cat "$tmp_body")
  rm -f "$tmp_body"

  if [[ "$http_code" == "201" ]]; then
    PR_URL=$(echo "$response" | jq -r '.links.html.href')
    log_info "PR created: ${PR_URL}"
    return 0
  fi

  log_error "Bitbucket PR creation failed (HTTP ${http_code}): $(echo "$response" | jq -r '.error.message // empty')"
  return 1
}

# ==========================================================================
# Rollback (I-9)
# ==========================================================================

# ---------------------------------------------------------------------------
# handle_rollback <wp_id>
# Undo a previous generation: close PR, delete branch, revert status.
# ---------------------------------------------------------------------------
handle_rollback() {
  local wp_id="$1"

  local summary_file="${LOG_DIR:-./logs}/run-summary.jsonl"
  if [[ ! -f "$summary_file" ]]; then
    log_error "No run-summary.jsonl found. Nothing to rollback."
    exit 2
  fi

  # Find the most recent entry for this WP
  local entry
  entry=$(grep "\"wp_id\":${wp_id}" "$summary_file" | tail -1)
  if [[ -z "$entry" ]]; then
    log_error "No run history found for WP #${wp_id}"
    exit 2
  fi

  local branch pr_url
  branch=$(echo "$entry" | jq -r '.branch // empty')
  pr_url=$(echo "$entry" | jq -r '.pr_url // empty')

  # Confirm with user
  echo "Rollback WP #${wp_id}:"
  [[ -n "$branch" ]] && echo "  - Delete branch: ${branch}"
  [[ -n "$pr_url" ]] && echo "  - Close PR: ${pr_url}"
  echo "  - Revert OP status"
  printf "Proceed? [y/N] "
  local answer
  read -r answer
  if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
    echo "Rollback cancelled."
    return 0
  fi

  # Close PR
  if [[ -n "$pr_url" ]]; then
    rollback_close_pr "$pr_url"
  fi

  # Delete branch
  if [[ -n "$branch" ]]; then
    rollback_delete_branch "$branch"
  fi

  # Revert status
  rollback_revert_status "$wp_id"

  echo "✅ Rollback complete for WP #${wp_id}"
}

# ---------------------------------------------------------------------------
# rollback_close_pr <pr_url>
# Close/decline the PR on the hosting platform.
# ---------------------------------------------------------------------------
rollback_close_pr() {
  local pr_url="$1"

  if [[ "$pr_url" == *"github.com"* ]]; then
    # Resolve token from CLI auth
    local token
    token="$(_resolve_git_token "github")"
    if [[ -z "$token" ]]; then
      log_warn "No GitHub auth token. Close PR manually: ${pr_url}"
      return 0
    fi

    # Extract owner/repo/number from URL
    local pr_path
    pr_path=$(echo "$pr_url" | sed 's|.*github.com/||;s|/pull/|/pulls/|')
    local api_url="https://api.github.com/repos/${pr_path}"
    curl --silent --max-time 15 \
      -H "Authorization: Bearer ${token}" \
      -H "Accept: application/vnd.github+json" \
      -X PATCH \
      --data '{"state":"closed"}' \
      "$api_url" > /dev/null 2>&1 || true
    log_info "PR closed: ${pr_url}"

  elif [[ "$pr_url" == *"gitlab.com"* ]]; then
    log_warn "GitLab MR close via URL not implemented. Close manually: ${pr_url}"

  elif [[ "$pr_url" == *"bitbucket.org"* ]]; then
    log_warn "Bitbucket PR decline via URL not implemented. Decline manually: ${pr_url}"

  else
    log_warn "Unknown PR platform. Close manually: ${pr_url}"
  fi
}

# ---------------------------------------------------------------------------
# rollback_delete_branch <branch_name>
# Delete remote and local branch, checkout base.
# ---------------------------------------------------------------------------
rollback_delete_branch() {
  local branch_name="$1"

  # Delete remote branch
  git -C "$REPO_ROOT" push "${GIT_REMOTE}" --delete "${branch_name}" 2>/dev/null || {
    log_warn "Could not delete remote branch ${branch_name} (may not exist)"
  }

  # Checkout base branch
  git -C "$REPO_ROOT" checkout "${GIT_BASE_BRANCH}" --quiet 2>/dev/null || true

  # Delete local branch
  git -C "$REPO_ROOT" branch -D "${branch_name}" 2>/dev/null || {
    log_warn "Could not delete local branch ${branch_name} (may not exist)"
  }

  log_info "Branch deleted: ${branch_name}"
}

# ---------------------------------------------------------------------------
# rollback_revert_status <wp_id>
# Revert OP status to pickup_status and post comment.
# ---------------------------------------------------------------------------
rollback_revert_status() {
  local wp_id="$1"

  local pickup_id
  pickup_id=$(config_get_status_id "pickup_status")

  if [[ -n "$pickup_id" ]]; then
    op_update_wp_status "$wp_id" "$pickup_id" || true
  fi

  op_post_comment "$wp_id" "⏪ forgeplan rollback: Code generation reverted. Branch and PR deleted." || true
}
